name: healjai_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rive: ^0.13.20
  go_router: ^16.0.0
  flutter_svg: ^2.2.0
  provider: ^6.1.5
  google_fonts: ^6.2.1
  http: ^1.4.0
  lottie: ^3.3.1
  animate_do: ^4.2.0
  firebase_core: ^3.15.2
  google_sign_in: ^5.4.2
  firebase_auth: ^5.7.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.2.1
  carousel_slider: ^5.1.1
  smooth_page_indicator: ^1.2.1
  fluttertoast: ^8.2.12
  shimmer: ^3.0.0
  pin_code_fields: ^8.0.1
  intl: ^0.20.2
  socket_io_client: ^3.1.2
  percent_indicator: ^4.2.5
  image_picker: ^1.2.0
  flutter_secure_storage: ^9.2.4
  dotted_border: ^3.1.0
  photo_view: ^0.15.0
  table_calendar: ^3.2.0
  flip_card: ^0.7.0
  firebase_storage: ^12.4.10
  timeago: ^3.7.1
  audioplayers: ^6.0.0
  flutter_spinkit: ^5.2.2
  flame: ^1.11.0
  toastification: ^3.0.3
  flame_audio: ^2.8.0
  cached_network_image: ^3.4.1
  just_audio: ^0.9.36  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4   # 👈 อัปเดตเป็นเวอร์ชันล่าสุด

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/animations/rives/
    - assets/animations/lotties/
    - assets/audio/
    - .env

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/app_icon.png"
  image_path_ios: "assets/icons/app_icon.png"
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"


