// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHoAxP5cIKiY-g0ArwpKiCq7Esr1S2T_U',
    appId: '1:307519523878:android:7693c5c405e9302a33eae7',
    messagingSenderId: '307519523878',
    projectId: 'healjaiapp-60ec3',
    storageBucket: 'healjaiapp-60ec3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr95V7X1zwKkdJk99toFIQo03IYkSEBpE',
    appId: '1:307519523878:ios:c94de5baa86eccba33eae7',
    messagingSenderId: '307519523878',
    projectId: 'healjaiapp-60ec3',
    storageBucket: 'healjaiapp-60ec3.firebasestorage.app',
    androidClientId: '307519523878-l6ejks340nmhn9jspv1ab74psjeganj6.apps.googleusercontent.com',
    iosClientId: '307519523878-c1cfr0fvkj54vi45t628qi2n1g2qqhcp.apps.googleusercontent.com',
    iosBundleId: 'com.example.healjaiProject',
  );

}